output_directory = string(default='/Users/pierre/Desktop/MICADO/Simul_MICADO/Simul/OUTPUT/')
input_directory = string(default='/Users/pierre/Desktop/MICADO/Simul_MICADO/Simul/INPUT/')
# save the final coronagraphic img in fits file
save_fits_img = boolean(default=True)
# save the lyot plane intensity (before,after) in fits file
save_fits_lyot = bool_list(default=list(False,False))
# save individual monochromatic images in a cube (only possible if n_images=1)
save_fits_poly = boolean(default=False)
# save the checking plots as png files (only possible if n_images = 1)
save_png = boolean(default='False')

[simuconfig]
    # number of final images in the cube
    n_images   = integer(min=1,default=1)
    # number of simulated images to be averaged to produce 1 frame
    # (different turbulent screen, rotating aberr per sub-image)
    n_img_mean = integer(min=1,default=1)
    delta_t = float(default=1.) # [s] time between images for ADI
    zenith_distance = float(min=-90.,max=90.,default=20.) # [deg] zenith distance
    tel_diameter = float(default=38.) # [m] telescope diameter
    tel_latitude = float(default=-24.5) # [deg] telescope site latitude
    centering = option('FFTSTYLE','SYMMETRIC',default='FFTSTYLE') # centering style for the simulated PSF 
    # centering can be 'FFTSTYLE': centered on pixel dim/2,dim/2
    # or 'SYMMETRIC': centering between pixes dims/2-1 and dim/2

[planetconfig]
    # Mode 1 : Science planet: rotates with parallactic angle
    planet_ON = boolean(default=False)
    dist_planet = float(default=0) # [lbd_min/D] angular separation of the planet defined for lambda_min
    planet_pa = float(default=0.) # [deg] position angle
    # Mode 2 : For throughput estimation as a function of angular separation, in a the direction given by planet_pa, and for n_images different separations between dist_minmax separation limits    
    planet_throughput = boolean(default=False) # For throughput estimation as a function of angular separation, in a 
    dist_minmax = float_list(default=list(0., 10.)) # [lbd_min/D] angular separation, defined for lambda_min

[waveconfig]
    n_wave = integer(min=1,default=3) # number of simulated wavelength channels
    lbd0 = float(default=2.1) # [um] central wavelength 
    delta_lbd = float(default=0.1) # [µm] spectral bandwidth

[aberrconfig]
    #   Noll-Zernike numbering: 
    #   piston, tip, tilt, focus, astig1, astig2, coma1, coma2, Z9, Z10, ...
    #   RMS in microns

    # --- pre-corono Zernike aberrations: applied in entrance pupil
    pre_zernike_ON = boolean(default=False)
    pre_z_coeff = float_list(default=list(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0))
    pre_z_slope = float_list(default=list(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0)) # nm/min

    # --- pre-corono aberrations from fits
    pre_aberr_fits = boolean(default=False) # phase screen loaded from fits file
    pre_aberr_file = string_list(default=list())
    pre_amp_fits = boolean(default=False) # amplitude screen loaded from fits file
    pre_amp_file = string_list(default=list())

    # --- [SPHERE UPGRADE]
    sphere_jitter = boolean(default=False)
    sph_jitter_file = string(default=None)

    # --- post-corono Zernike aberrations: applied in Lyot plane
    post_zernike_ON = boolean(default=False)
    post_z_coeff = float_list(default=list(0.0, 0.0, 0.0, 0.0, 0, 0.0, 0.0, 0.0))
    
    # --- post-corono aberrations from fits
    post_aberr_fits = boolean(default=False)
    post_aberr_file = string(default=None)

    # Residual Turbulent Phase [COMPASS]
    turbu_ON = boolean(default=False)
    turbu_directory = string(default='TURBU/')
    turbu_prefix = string(default=None)
    turbu_remove_tt = boolean(default=False)
    turbu_delta_n_phase = integer(default=1)
    turbu_file_nb_init = integer(default=0)
    
    # Static aberrations: OPD screen computed from PSD
    static_fits = boolean(default=False)
    static_file = string(default=None)
    static_rms_nm = float(default=0.0) # [nm] rms
    
    # Rotating aberrations: OPD screen computed from PSD
    rotat_fits = boolean(default=False)
    rotat_file = string(default=None)
    rotat_rms_nm = float(default=0.0) # [nm] rms
    
    # Atmospheric refraction
    atm_refrac_ON = boolean(default=True)
    post_ADC_ON = boolean(default=True) 
    pressure = float(default=534.0)
    temperature = float(default=10.0) # [deg]
    rel_humidity = float(default=20.0) # [%]
    refrac_angle = float(default=90.0) # [deg] direction of atmospheric refraction, 90deg for vertical

[coroconfig]
    # PUPIL PLANE DEFINITION ########################################

    # - ENTRANCE PUPIL ----------------------------------------------
    pup_fits = boolean(default=False) # loaded from fits file
    # -- loaded from fits file    
    pup_file = string(default=None)
    pup_radius_in_fits = float(default=512) # pupil radius in fits file
    # -- defined from dimensions given by user
    grid_width = integer(default=1024)
    pup_ratio = float(max=1., default=0.5)
    pup_obst = float(max=1.,default=0.30) # [%] in percent of the pupil diameter

    # - ENTRANCE PUPIL APODIZATION ----------------------------------
    # -- amplitude apodization
    pre_apod_fits = boolean(default=False) # loaded from fits file
    pre_apod_file = string(default=None)
    pre_phas_fits = boolean(default=False) # loaded from fits file
    pre_phas_file = string(default=None)

    # - LYOT STOP ---------------------------------------------------
    lyot_fits = boolean(default=False)
    lyot_file = string(default=None) # loaded from fits file
    # -- defined from dimensions given by user    
    lyot_out = float(max=1., default=0.88) # [%] in percent of the entrance pupil diameter
    lyot_in = float(max=1., default=0.4) # [%] in percent of the entrance pupil diameter
    # -- lyot mask alignment
    lyot_shift = float_list(default=list(0.0, 0.0)) # [%] ramp amplitude in percent of the entrance pupil diameter
    lyot_drift = float_list(default=list(0.0, 0.0)) # [%] drift rates in percent of the entrance pupil diameter per hour
    # drift > 0: from left to right, bottom to top    

    # - FOCAL PLANE DEFINITION ######################################
    fp_mask = option('occulter','vortex','fqpm','nomask','vapp',default='nomask')
    
    [[occulter]]    # occulter definition for Lyot coro
        # occulter radius in mas
        occulter_rad = float(default=50.68) # [mas] small: 25.34 / large: 50.68
        mft_sampling = integer(default=100) # MFT sampling at focal plane
    
    [[vortex]]    # vortex phase mask definition
        v_charge      = float(default=2)
        v_offset      = float(default=0.) # [deg]
        v_sign        = float(min = -1., max=1., default=1.)
        fp_sampling   = float(default=6)    # 6 for charge 2, 12 for charge 4
        fp_fov        = float(default=256)
    
    [[fqpm]]    # FQPM phase mask definition
        fp_sampling = integer(default=6)
        fp_fov = integer(default=256)

    [[vapp]]    # v-APP pupil plane phase mask definition
        vapp_phase_file = string(default=None)
        vapp_grating = boolean(default=False) # if True, the second off-axis PSF will be computed with minus phase
        vapp_leakage = float(default=0.) # leakage term, in percents

    [[paplc]]
        fp_sampling = integer(default=8)
        fp_fov = integer(default=384)
        fp_mask_file = string(default=None)
        paplc_phase_file = string(default=None)

[detectorconfig]
    detector_fov = float(default=64) # [l/D] full FoV width
    detector_sampling = float(default=3.) # [pix per l/D]
